modif tx_manager,add wc_queue,add new handlers and change struct of s…
Igor-makeev/miborchestrator pull request #1
Opened 2023-02-15 13:58 UTC by Igor-makeev

…ervice

2023-02-19 02:43 UTC, capsulated requested changes
Пока маловато))) 

По ридми написал - рисунок + описание алгоритма шардирования. 

И обязательно main пустой, чтобы можно было ревьюить

2023-02-19 02:43 UTC, capsulated commented on README.md
> +Сервис оркестратор распределяет транзакции между [шардами](https://github.com/Igor-makeev/mibshard).
ссылка на этот же репозиторий 😕

2023-02-19 02:43 UTC, capsulated commented on README.md
> +![Screenshot from 2023-02-17 20-49-45](https://user-images.githubusercontent.com/67610606/219625570-03023fd9-a235-49a7-be25-5dfbedbd4844.png)
Третий postgres появился справа, без номера шарда. Что-то поменялось?

2023-02-19 02:43 UTC, capsulated commented on README.md
> +Данный проект представляет собой распределительную систему с механизмом межшардовых транзакций, состояющу из сервиса оркестратора и сервисов [шардов](https://github.com/Igor-makeev/mibshard).
Так и не описал по какому принципу будет шардирование происходить. Алгоритм реализации шардирования обязательно добавить тогда, также как и архитектуру, в виде картинки. API, сервер и остальное - рисовать не нужно. 

Описание АПИ эндпоинтов очень много получилось, уверен, что успеешь сделать?

2023-02-19 02:43 UTC, capsulated commented on internal/service/service.go
> -func NewService(Config *config.Config) *Service {
Оу, у тебя main  не пустой, не смогу проверять нормально.

Сотри и по новой залей. git push force, rollback или вообщеможно скопировать и по-новой репозиторий создать

2023-02-20 14:17 UTC, Igor-makeev commented on README.md
> +Сервис оркестратор распределяет транзакции между [шардами](https://github.com/Igor-makeev/mibshard).
ссылка на другую репу

2023-02-20 14:18 UTC, Igor-makeev commented on README.md
> +![Screenshot from 2023-02-17 20-49-45](https://user-images.githubusercontent.com/67610606/219625570-03023fd9-a235-49a7-be25-5dfbedbd4844.png)
у оркестратора теперь по задумке есть персистентное хранилище где хранятся пользователи и есть журнал транзакций

2023-02-20 14:19 UTC, Igor-makeev commented on internal/service/service.go
> -func NewService(Config *config.Config) *Service {
ок

2023-02-20 14:28 UTC, closed without merging